### ISSUE TITLE
pretrained VGG_ILSVRC_16_layers.caffemodel

### ISSUE THREAD

**Issue by flyhighwjw** [gombru/pycaffeFCNTemplate#1]
@gombru Hello, can you share it with  the pretrained text VGG_ILSVRC_16_layers.caffemodel? thank you!

**Comment by gombru** [comment]
The TextFCN repo is here https://github.com/gombru/TextFCN

**Comment by flyhighwjw** [comment]
thank you for sharing，I've got it.
